# Generated by Django 4.2.13 on 2024-05-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_about_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='about_info',
        ),
    ]
